name: Build and Deploy Spring PetClinic Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    - name: Set up Apache Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Navigate to the spring-petclinic directory
      run: cd spring-petclinic/spring-petclinic

    - name: Initialize and update submodules
      run: |
        git submodule update --init --recursive

    - name: Build the Spring PetClinic Application
      run: |
        mvn clean verify -DskipTests=true

    - name: Archive the JAR file
      uses: actions/upload-artifact@v4
      with:
        name: petclinic-jar
        path: spring-petclinic/spring-petclinic/target/*.jar


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download JAR artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: petclinic-jar

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container App using az containerapp up
      run: |
        az containerapp up \
          --resource-group ${{ secrets.resourceGroupName }} \
          --name spring-petclinic-app \
          --subscription ${{ secrets.subscriptionId }} \
          --location ${{ secrets.location }} \
          --environment ${{ secrets.environmentName }} \
          --artifact petclinic-jar/*.jar \
          --ingress external \
          --target-port 8080 \
          --query properties.configuration.ingress.fqdn
